name: tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  run-tests:
    name: pytest
    runs-on: ubuntu-latest
    env:
      UV_SYSTEM_PYTHON: 1

    steps:
      - uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v3

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: setup project
        run: uv pip sync --system requirements-dev.txt

      - name: run tests
        run: uv run pytest --cov -s -v test_main.py